-- MySQL Script generated by MySQL Workbench
-- Wed Jul 27 00:28:24 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema regatta
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `regatta` ;

-- -----------------------------------------------------
-- Schema regatta
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `regatta` ;
USE `regatta` ;

-- -----------------------------------------------------
-- Table `regatta`.`class`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `regatta`.`class` ;

CREATE TABLE IF NOT EXISTS `regatta`.`class` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_class` ON `regatta`.`class` (`id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `regatta`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `regatta`.`category` ;

CREATE TABLE IF NOT EXISTS `regatta`.`category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_UNIQUE` ON `regatta`.`category` (`id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `regatta`.`builder`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `regatta`.`builder` ;

CREATE TABLE IF NOT EXISTS `regatta`.`builder` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_UNIQUE` ON `regatta`.`builder` (`id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `regatta`.`architect`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `regatta`.`architect` ;

CREATE TABLE IF NOT EXISTS `regatta`.`architect` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_UNIQUE` ON `regatta`.`architect` (`id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `regatta`.`country`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `regatta`.`country` ;

CREATE TABLE IF NOT EXISTS `regatta`.`country` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(45) NULL,
  `name` VARCHAR(45) NOT NULL,
  `fullName` VARCHAR(255) NULL,
  `iso3` VARCHAR(45) NULL,
  `number` VARCHAR(45) NULL,
  `continentCode` VARCHAR(45) NULL,
  `order` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_country` ON `regatta`.`country` (`id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `regatta`.`vessel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `regatta`.`vessel` ;

CREATE TABLE IF NOT EXISTS `regatta`.`vessel` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idVesselClass` INT NOT NULL,
  `idVesselCategory` INT NOT NULL,
  `idVesselBuilder` INT NOT NULL,
  `idVesselArchitect` INT NOT NULL,
  `idVesselCountry` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `yearOfBuilt` DATE NULL,
  `lengthOverall` INT NULL,
  `lengthWaterline` INT NULL,
  `beam` VARCHAR(255) NULL,
  `draft` VARCHAR(255) NULL,
  `keel` VARCHAR(255) NULL,
  `deck` VARCHAR(255) NULL,
  `weight` INT NULL,
  `displacement` INT NULL,
  `ballast` INT NULL,
  `rigging` INT NULL,
  `hull` VARCHAR(255) NULL,
  `hullMaterial` VARCHAR(255) NULL,
  `hullColor` VARCHAR(255) NULL,
  `hullNumber` VARCHAR(255) NULL,
  `engine` VARCHAR(255) NULL,
  `fuelType` VARCHAR(255) NULL,
  `sailNumber` VARCHAR(45) NULL,
  `rating` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_vessel_class`
    FOREIGN KEY (`idVesselClass`)
    REFERENCES `regatta`.`class` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vessel_category`
    FOREIGN KEY (`idVesselCategory`)
    REFERENCES `regatta`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vessel_builder`
    FOREIGN KEY (`idVesselBuilder`)
    REFERENCES `regatta`.`builder` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vessel_architect`
    FOREIGN KEY (`idVesselArchitect`)
    REFERENCES `regatta`.`architect` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vessel_country`
    FOREIGN KEY (`idVesselCountry`)
    REFERENCES `regatta`.`country` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_vessel` ON `regatta`.`vessel` (`id` ASC) VISIBLE;

CREATE INDEX `id_vessel_class` ON `regatta`.`vessel` (`idVesselClass` ASC) VISIBLE;

CREATE INDEX `id_vessel_category` ON `regatta`.`vessel` (`idVesselCategory` ASC) VISIBLE;

CREATE INDEX `id_vessel_builder` ON `regatta`.`vessel` (`idVesselBuilder` ASC) VISIBLE;

CREATE INDEX `id_vessel_architect` ON `regatta`.`vessel` (`idVesselArchitect` ASC) VISIBLE;

CREATE INDEX `id_vessel_country` ON `regatta`.`vessel` (`idVesselCountry` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `regatta`.`continent`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `regatta`.`continent` ;

CREATE TABLE IF NOT EXISTS `regatta`.`continent` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `code` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_continent` ON `regatta`.`continent` (`id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `regatta`.`status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `regatta`.`status` ;

CREATE TABLE IF NOT EXISTS `regatta`.`status` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_status` ON `regatta`.`status` (`id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `regatta`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `regatta`.`role` ;

CREATE TABLE IF NOT EXISTS `regatta`.`role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_UNIQUE` ON `regatta`.`role` (`id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `regatta`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `regatta`.`user` ;

CREATE TABLE IF NOT EXISTS `regatta`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `userHash` VARCHAR(255) NOT NULL,
  `idUserRole` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_user_role`
    FOREIGN KEY (`idUserRole`)
    REFERENCES `regatta`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_user` ON `regatta`.`user` (`id` ASC) VISIBLE;

CREATE INDEX `fk_users_role1_idx` ON `regatta`.`user` (`idUserRole` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `regatta`.`serie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `regatta`.`serie` ;

CREATE TABLE IF NOT EXISTS `regatta`.`serie` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_serie` ON `regatta`.`serie` (`id` ASC) INVISIBLE;


-- -----------------------------------------------------
-- Table `regatta`.`event`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `regatta`.`event` ;

CREATE TABLE IF NOT EXISTS `regatta`.`event` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `idEventCountry` INT NOT NULL,
  `description` BLOB NULL,
  `site` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_event_country`
    FOREIGN KEY (`idEventCountry`)
    REFERENCES `regatta`.`country` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idEvent` ON `regatta`.`event` (`id` ASC) VISIBLE;

CREATE INDEX `idEvenetCountry` ON `regatta`.`event` (`idEventCountry` ASC) INVISIBLE;


-- -----------------------------------------------------
-- Table `regatta`.`institution`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `regatta`.`institution` ;

CREATE TABLE IF NOT EXISTS `regatta`.`institution` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(255) NULL,
  `url` VARCHAR(45) NULL,
  `idInstitutionCountry` INT NULL,
  `phoneNumber` VARCHAR(255) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_institution_country`
    FOREIGN KEY (`id`)
    REFERENCES `regatta`.`country` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idInstitution` ON `regatta`.`institution` (`id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `regatta`.`type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `regatta`.`type` ;

CREATE TABLE IF NOT EXISTS `regatta`.`type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_type` ON `regatta`.`type` (`id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `regatta`.`regatta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `regatta`.`regatta` ;

CREATE TABLE IF NOT EXISTS `regatta`.`regatta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `number` INT NULL,
  `eventDate` DATE NOT NULL,
  `hourDate` VARCHAR(45) NULL,
  `positionSerie` INT NULL,
  `positionGeneral` INT NULL,
  `startTime` TIMESTAMP NULL,
  `finishTime` TIMESTAMP NULL,
  `realTime` TIMESTAMP NULL,
  `correctedTime` TIMESTAMP NULL,
  `points` INT NULL,
  `seriePosition` INT NULL,
  `generalPosition` INT NULL,
  `idInstitutionOrganizer` INT NOT NULL,
  `idType` INT NOT NULL,
  `idEvent` INT NOT NULL,
  `idSerie` INT NOT NULL,
  `idStatus` INT NOT NULL,
  `idVessel` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_regatta_institution`
    FOREIGN KEY (`idInstitutionOrganizer`)
    REFERENCES `regatta`.`institution` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_regatta_type`
    FOREIGN KEY (`idType`)
    REFERENCES `regatta`.`type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_regatta_event`
    FOREIGN KEY (`idEvent`)
    REFERENCES `regatta`.`event` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_regatta_serie`
    FOREIGN KEY (`idSerie`)
    REFERENCES `regatta`.`serie` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_regatta_status`
    FOREIGN KEY (`idStatus`)
    REFERENCES `regatta`.`status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_regatta_vessel`
    FOREIGN KEY (`idVessel`)
    REFERENCES `regatta`.`vessel` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idRegatta` ON `regatta`.`regatta` (`id` ASC) VISIBLE;

CREATE INDEX `idInstitutionRegatta` ON `regatta`.`regatta` (`idInstitutionOrganizer` ASC) VISIBLE;

CREATE INDEX `idTypeRegatta` ON `regatta`.`regatta` (`idType` ASC) VISIBLE;

CREATE INDEX `idEventRegatta` ON `regatta`.`regatta` (`idEvent` ASC) VISIBLE;

CREATE INDEX `idSerieRegatta` ON `regatta`.`regatta` (`idSerie` ASC) VISIBLE;

CREATE INDEX `idStatusRegatta` ON `regatta`.`regatta` (`idStatus` ASC) VISIBLE;

CREATE INDEX `idVesselRegatta` ON `regatta`.`regatta` (`idVessel` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `regatta`.`users_has_vessel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `regatta`.`users_has_vessel` ;

CREATE TABLE IF NOT EXISTS `regatta`.`users_has_vessel` (
  `idUser` INT NOT NULL,
  `idVessel` INT NOT NULL,
  PRIMARY KEY (`idUser`, `idVessel`),
  CONSTRAINT `fk_user_vessel`
    FOREIGN KEY (`idUser`)
    REFERENCES `regatta`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vessel_user`
    FOREIGN KEY (`idVessel`)
    REFERENCES `regatta`.`vessel` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_users_has_vessel_vessel1_idx` ON `regatta`.`users_has_vessel` (`idVessel` ASC) VISIBLE;

CREATE INDEX `fk_users_has_vessel_users1_idx` ON `regatta`.`users_has_vessel` (`idUser` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
